#!/bin/sh

PACKAGE_NAME="VideoRenamer"
APP_PATH="/usr/syno/synoman/webman/3rdparty/$PACKAGE_NAME"
APP_TARGET_PATH="/var/packages/$PACKAGE_NAME/target"

JOB_PATH="${APP_TARGET_PATH}/cfg"
JOB_FILENAME="crontab.job"
#JOB_TIME="jobtime.cfg"

#for crontab to be changed timer_delete=videorenamer.sh
MAIN_SCRIPT_FULL_PATH="/var/packages/VideoRenamer/target/scripts/videorenamer.sh"
timer_scriptname=$(echo "$MAIN_SCRIPT_FULL_PATH" | sed 's/ $//;s#.*/bin/bash ##')
timer_delete=$(echo "$timer_scriptname" | sed 's/.*\///g')

APP_TMP_PATH="/var/packages/$PACKAGE_NAME/target/tmp"

VR_APP_LOG_PATH="${APP_TARGET_PATH}/log"
VR_APP_CFG_PATH="${APP_TARGET_PATH}/cfg"
VR_APP_TMP_PATH="${APP_TARGET_PATH}/tmp"

# check where Video Station is installed
COUNTER=1
while [  $COUNTER -lt 100 ]; do
	if [ -e "/volume$COUNTER/@appstore/VideoStation" ]; 
		then 
			VideoStationVolume="volume$COUNTER"
			break
	fi
	let COUNTER=COUNTER+1 
done

#ConfFilePath="/$VideoStationVolume/video/VideoRenamer.cfg"
ConfFilePath="${APP_TARGET_PATH}/cfg/VideoRenamer.cfg"

# build tmp folder if not exist
if [ ! -e "/tmp/$PACKAGE_NAME/" ];
	then 
		mkdir "/tmp/$PACKAGE_NAME/"
fi
if [ ! -e "/tmp/$PACKAGE_NAME/cfg/" ];
	then 
		mkdir "/tmp/$PACKAGE_NAME/cfg/"
fi
if [ ! -e "/tmp/$PACKAGE_NAME/tmp/" ];
	then 
		mkdir "/tmp/$PACKAGE_NAME/tmp/"
fi


DO_ADD_CRON_TASK ()
{
	#HourToRun="$(cut -f2 "$JOB_PATH/$JOB_FILENAME")"
	#if [ -z "$HourToRun" ];
	#	then
	#		echo "0	1	*	*	*	root	$MAIN_SCRIPT_FULL_PATH" > "$JOB_PATH/$JOB_FILENAME"
	#fi

	cat "$JOB_PATH/$JOB_FILENAME" >>/etc/crontab
	#cp "/etc/crontab" "/volume1/Dev/dev/"
	#echo "*	12	*	*	*	root	$MAIN_SCRIPT_FULL_PATH" >>/etc/crontab
	# Restart the cron deamon
	#synoservice -restart crond
	#/usr/syno/sbin/synoservicecfg --restart crond
	#/usr/syno/sbin/synoservicectl --restart crond
	#/usr/syno/sbin/synoservice --restart crond
	#sudo /usr/syno/sbin/synoservice --restart crond
	/usr/syno/sbin/synoservicectl --reload crond
} 


DO_REMOVE_CRON_TASK()
{
	# remove the cron task
	sed -i "/"$timer_delete"/d" "/etc/crontab"
}


DO_CHECK_CONF_FILE ()
{
#does the conf file exist
if [ ! -e "$ConfFilePath" ]; 
	then 
		cp "/var/packages/$PACKAGE_NAME/target/cfg/V.R.cfg" $ConfFilePath
fi
}

DO_BACKUP()
{

	if [ ! -e "/tmp/$PACKAGE_NAME/" ]; 
		then
			mkdir -p "/tmp/$PACKAGE_NAME/"
	fi	
	# backup tmp
	if [ -e "$APP_TMP_PATH/" ];
		then
			rsync -av "$APP_TMP_PATH/" "/tmp/$PACKAGE_NAME/tmp/"
	fi
	# backup cfg
	if [ -e "${APP_TARGET_PATH}/cfg/" ];
		then
			rsync -av --exclude "V.R.cfg" "${APP_TARGET_PATH}/cfg/" "/tmp/$PACKAGE_NAME/cfg/"
	fi
		# backup cfg
	if [ -e "${APP_TARGET_PATH}/log/" ];
		then
			rsync -av "${APP_TARGET_PATH}/log/" "/tmp/$PACKAGE_NAME/log/"
	fi
}

DO_RESTORE()
{
	# restore resume
	if [ -e "/tmp/$PACKAGE_NAME/tmp/" ];
		then
			rsync -av "/tmp/$PACKAGE_NAME/tmp/" "$APP_TMP_PATH/"
	fi
	# restore conf files
	if [ -e "/tmp/$PACKAGE_NAME/cfg/" ];
		then
			rsync -av --exclude "V.R.cfg" "/tmp/$PACKAGE_NAME/cfg/" "${APP_TARGET_PATH}/cfg/"
	fi
			# backup cfg
	if [ -e "/tmp/$PACKAGE_NAME/log/" ];
		then
			rsync -av "/tmp/$PACKAGE_NAME/log/" "${APP_TARGET_PATH}/log/"
	fi
}

# check where Video Station is installed
COUNTER=1
while [ $COUNTER -lt 100 ]; do
	if [ -e "/volume$COUNTER/@appstore/VideoStation" ]; 
		then 
			VideoStationVolume="volume$COUNTER"
			break
	fi
	let COUNTER=COUNTER+1 
done
VR_VideoStation_Folder="/$VideoStationVolume/video"

if [ -e "$VR_VideoStation_Folder/debug" ];
	then
		if [ ! -e "$VR_VideoStation_Folder/VideoRenamer/log" ];
			then 
				mkdir -p "$VR_VideoStation_Folder/VideoRenamer/log"
				echo "$(date +"%F %T") : $VR_VideoStation_Folder/VideoRenamer/log created" >>"$VR_VideoStation_Folder/VideoRenamer/log/var.sh.log"
		fi
		if [ ! -e "$VR_VideoStation_Folder/VideoRenamer/tmp" ];
			then 
				mkdir -p "$VR_VideoStation_Folder/VideoRenamer/tmp"
				echo "$(date +"%F %T") : $VR_VideoStation_Folder/VideoRenamer/tmp created" >>"$VR_VideoStation_Folder/VideoRenamer/log/var.sh.log"
		fi
		if [ ! -e "$VR_VideoStation_Folder/VideoRenamer/cfg" ];
			then 
				mkdir -p "$VR_VideoStation_Folder/VideoRenamer/cfg"
				echo "$(date +"%F %T") : $VR_VideoStation_Folder/VideoRenamer/cfg created" >>"$VR_VideoStation_Folder/VideoRenamer/log/var.sh.log"
		fi
		chmod -R 777 "$VR_VideoStation_Folder/VideoRenamer/"
		if [ ! -e "/tmp/VideoRenamer/tmp" ];
			then 
				mkdir -p "/tmp/VideoRenamer/tmp"
				echo "$(date +"%F %T") : /tmp/VideoRenamer/tmp created" >>"$VR_VideoStation_Folder/VideoRenamer/log/var.sh.log"
		fi
		if [ ! -e "/tmp/VideoRenamer/log" ];
			then 
				mkdir -p "/tmp/VideoRenamer/log"
				echo "$(date +"%F %T") : /tmp/VideoRenamer/log created" >>"$VR_VideoStation_Folder/VideoRenamer/log/var.sh.log"
		fi
		if [ ! -e "/tmp/VideoRenamer/cfg" ];
			then 
				mkdir -p "/tmp/VideoRenamer/cfg"
				echo "$(date +"%F %T") : /tmp/VideoRenamer/cfg created" >>"$VR_VideoStation_Folder/VideoRenamer/log/var.sh.log"
		fi
		chmod -R 777 "/tmp/VideoRenamer/"
fi