#!/bin/sh

. /var/packages/VideoRenamer/scripts/common
#. `dirname $0`/common

DO_BACKUP &&

#rm "$JOB_PATH/$JOB_FILENAME"

#MinuteToRun="$(grep 'hour: ' "${JOB_PATH}$JOB_TIME")"
#MinuteToRun="${MinuteToRun:8}"
#HourToRun="$(grep 'hour: ' "${JOB_PATH}$JOB_TIME")"
#HourToRun="${HourToRun:6}"
#DayOfMonthToRun="$(grep 'hour: ' "${JOB_PATH}$JOB_TIME")"
#DayOfMonthToRun="${DayOfMonthToRun:14}"
#MonthToRun="$(grep 'hour: ' "${JOB_PATH}$JOB_TIME")"
#MonthToRun="${MonthToRun:7}"
#DayOfWeekToRun="$(grep 'hour: ' "${JOB_PATH}$JOB_TIME")"
#DayOfWeekToRun="${DayOfWeekToRun:13}"

MinuteToRun="$(cut -f1 "$JOB_PATH/$JOB_FILENAME")"
HourToRun="$(cut -f2 "$JOB_PATH/$JOB_FILENAME")"
DayOfMonthToRun="$(cut -f3 "$JOB_PATH/$JOB_FILENAME")"
MonthToRun="$(cut -f4 "$JOB_PATH/$JOB_FILENAME")"
DayOfWeekToRun="$(cut -f5 "$JOB_PATH/$JOB_FILENAME")"


if [ "$pkgwizard_remove_config" = "true" ]; 
	then
		#delete_db
		. /var/packages/VideoRenamer/scripts/video_file_remove.sh
fi

exit 0
