#!/bin/bash

case "$1" in
    start)
	synosystemctl start ${SYNOPKG_PKGNAME}
        ;;
    stop)
	synosystemctl stop ${SYNOPKG_PKGNAME}
        ;;
    status)
        ;;
    log)
        echo ""
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac

exit 0
